image: openjdk:11

stages:
  - build

build:
  stage: build
  script:
    - echo "Compiling the code..."
    - cd $CI_PROJECT_DIR/water
    # - sh gradlew clean assemble
  artifacts:
    paths:
      - target/water-0.0.1-SNAPSHOT.jar
