server:
  address: 0.0.0.0
  port: 8080

spring:
  # konfigurasi untuk koneksi db
  datasource:
    driver-class-name: com.mysql.jdbc.Driver

    # sesuaikan nama database anda dengan di bawah ini
    url: jdbc:mysql://root:HylJsBQ6IMipPhShdR6w@containers-us-west-70.railway.app:6786/railway

    # sesuaikan dengan NAMA dan PASSWORD anda dengan username password di bawah ini
    username: root
    password: HylJsBQ6IMipPhShdR6w

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true

    # pembuatan database (create || create-drop || validate || update)
    hibernate.ddl-auto: create-drop

    show-sql: true
