server:
  port: 8080

spring:
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true

    hibernate:
      ddl-auto: create-drop

    show-sql: true

  sql:
    init:
      mode: always

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/water?useSSL=false&serverTimezone=Asia/Jakarta&characterEncoding=latin1
    username: root
    password:

  thymeleaf:
    prefix: classpath:/templates/
    cache: false

  web:
    resources:
      static-locations: classpath:/static/

  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
